### ISSUE TITLE
Arabic language name in Finnish fails

### ISSUE THREAD

**Issue by userpointfi** [punic/punic#418]
Hello,

I have encountered an odd issue which I can't fully explain.

`echo \Punic\Language::getName('ar','fi');`

I got:

```
Notice:  Trying to access array offset on value of type null in /home/customer/www/common/composer/vendor/punic/punic/src/Data.php on line 692

Fatal error:  Uncaught Punic\Exception\InvalidLocale: A valid locale should be a string, NULL received in /home/customer/www/common/composer/vendor/punic/punic/src/Data.php:682
Stack trace:
#0 /home/customer/www/common/composer/vendor/punic/punic/src/Data.php(719): Punic\Data::getLocaleAlternatives(NULL, false)
#1 /home/customer/www/common/composer/vendor/punic/punic/src/Data.php(654): Punic\Data::getLocaleAlternatives('fi')
#2 /home/customer/www/common/composer/vendor/punic/punic/src/Data.php(261): Punic\Data::getLocaleFolder('fi')
#3 /home/customer/www/common/composer/vendor/punic/punic/src/Language.php(75): Punic\Data::get('languages', 'fi')
#4 /home/customer/www/common/web/classes/Common/LanguageStrings.php(992): Punic\Language::getName('ar', 'fi')
#5 /home/customer/www/common/web/classes/Common/LanguageStrings.php(899): Common\LanguageStrings->updateLanguageStringsLanguage()
#6 /home/customer/www/dev.webcal.guru/classes/WebCalGuru/Administration.php(2312): Common\LanguageStrings->updateLanguageStrings()
#7 /home/custo in /home/customer/www/common/composer/vendor/punic/punic/src/Data.php on line 682
```

The issue seemed to be in Data.php, row 536

` $chunks = explode('-', str_replace('_', '-', strtolower($locale)));`

The output of strtolower($locale) is `fi-latn-fI` (notice capital I in the end). I tested with every way I could, the [strtolower('I')](url) always gave the same upper case I. I've tried everything possible, and it simply does not give lower case i.

When I changed strtolower to mb_strtolower, it started working again.

I cannot explain this. Is it just me, or is there some UTF8 sequence involved? Perhaps in a data file, under Finland territory, the ending I is some UTF8 character, which mb_strtolower recognises as I, but strtolower does not?

**Comment by mlocati** [comment]
I can't replicate this issue: which version of Punic are you using?

**Comment by mlocati** [comment]
Also, for PHP version older than 8.2, the behavior of `strtolower` may be affected by the PHP configured locale.
What's the output of this code for you?

```php
var_dump(setlocale(LC_ALL, '0');
```

You can also try to add this code at the very beginning of your PHP code, and see if punic works:

```php
setlocale(LC_ALL, 'C');
```

**Comment by userpointfi** [comment]
Thank you for replying. A strangest thing happened. Now I can't reproduce the issue anymore myself. And I tested in a lot of ways earlier. I assume this could be related to the PHP locale since my PHP version is 7.4.33 and I do not maintain the server. So it is possible a configuration has changed which affected this.

Btw, the var_dump(setlocale(LC_ALL, '0')); outputs 'C', which I guess it should. But now I can't test any more what its output was earlier.

I'm sorry for this unnecessary bug report.
